# Generated by Django 3.2.9 on 2022-03-18 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
