# Generated by Django 3.2.9 on 2022-03-18 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_takeappointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
