# Generated by Django 3.2.9 on 2023-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadditional',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_profile_photos'),
        ),
    ]
