# Generated by Django 3.2.9 on 2021-12-26 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211226_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='your_expertise',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
